from realsafe.defense.bit_depth_reduction import bit_depth_reduce, bit_depth_reduction
from realsafe.defense.jpeg_compression import jpeg_compress, jpeg_compression
from realsafe.defense.randomization import randomize, randomization